### ISSUE TITLE
InventoryClickEvent Error (paper build 145)

### ISSUE THREAD

**Issue by MrPranklez** [SoulsCode37/TradeSystem#5]
Received the following error in console while players were using the trade GUI.

`[14:30:19 ERROR]: Could not pass event InventoryClickEvent to TradeSystem vB5
java.lang.NullPointerException: null
at me.soul.tradesystem.users.UsersManager.getUser(UsersManager.java:40) ~[?:?]
at me.soul.tradesystem.listeners.InventoryClickListener.invManagement(InventoryClickListener.java:25) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor447.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-145]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-145]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-145]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-145]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2333) ~[patched_1.15.2.jar:git-Paper-145]
at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-145]
at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-145]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-145]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-145]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-145]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-145]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-145]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-145]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-145]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-145]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-145]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-145]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

**Comment by MrPranklez** [comment]
It seems to be an incompatibility issue when someone uses the built in armorstand editor CMI uses. Is there any way for this to be fixed on Tradesystem's end?

**Comment by SoulsCode37** [comment]
Mh, i released a new update just now, try it and let me know if it solved your issue. 
Thanks

**Comment by MrPranklez** [comment]
Seems to be fixed!! Thanks for the quick response time btw xD!!!

**Comment by SoulsCode37** [comment]
No problem! Let me know if there is any other problem!
