### ISSUE TITLE
An error after /spectatetrade <player>

### ISSUE THREAD

**Issue by swordin** [SoulsCode37/TradeSystem#7]
Hello, 

I'm admin on server (git-Paper-1104; MC: 1.11.2); and I put command /spectatetrade SK2LL

and I got this error: "An internal error occured while attempting to perfom this command"

In console:

[20:02:34 INFO]: Kepler issued server command: /spectatetrade SK2LL
[20:02:34 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'spectatetrade' in plugin TradeSystem vB5-S-2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:675) ~[PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1393) ~[PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1198) ~[PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:839) [PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
        at me.soul.tradesystem.users.UsersManager.getUser(UsersManager.java:40) ~[?:?]
        at me.soul.tradesystem.commands.CSpectateTrade.onCommand(CSpectateTrade.java:39) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PaperSpigot-1-112-190517.jar:git-Paper-1104]
        ... 15 more

**Comment by SoulsCode37** [comment]
Hello, the plugin project is currently abandoned. If someone wants can continue this project from the source code. Thanks

**Comment by swordin** [comment]
Cool. Few days ago it was not abandoned. And I trusted it ;(

**Comment by SoulsCode37** [comment]
It should be fixed
