### ISSUE TITLE
Could not pass event InventoryClickEvent to TradeSystem vB5-S-2

### ISSUE THREAD

**Issue by swordin** [SoulsCode37/TradeSystem#9]
Another problem:

[20:17:34 ERROR]: Could not pass event InventoryClickEvent to TradeSystem vB5-S-2
org.bukkit.event.EventException
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1898) ~[PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:839) [PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [PaperSpigot-1-112-190517.jar:git-Paper-1104]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException

>plugman reload TradeSystem
[20:17:36 INFO]: [TradeSystem] Disabling TradeSystem vB5-S-2
[20:17:36 ERROR]: Error occurred while disabling TradeSystem vB5-S-2 (Is it up to date?)
java.lang.NullPointerException
[20:17:38 INFO]: [TradeSystem] Enabling TradeSystem vB5-S-2
[20:17:38 INFO]: > Loading instances...
[20:17:38 INFO]: > Loading listeners...
[20:17:38 INFO]: > Loading commands...
[20:17:38 INFO]: TradeSystem has been enabled B5
[20:17:38 INFO]: [PlugMan] TradeSystem has been reloaded.

**Comment by SoulsCode37** [comment]
It should be fixed
